input_filename = "input.txt"              # 输入语料文件名，应位于程序所在目录
output_filename = "input_statistics.txt"  # 输出结果文件名，将输出到程序所在目录；若文件已存在，则覆盖
word_length = 2                           # 词的字数（范围为1-255）
freq_threshold = 10                       # 词频阈值：低于此值的词将被忽略
use_regex = false                         # 字符过滤方式：false则使用UTF-8值范围和额外字符，true则使用正则表达式
lower_limit = 19968                       # UTF-8值范围下限：19968即\u4e00，即"一"字，会被包含
upper_limit = 40959                       # UTF-8值范围上限：40959即\u9fff，即"鿿"字，会被包含
extra_chars = ""                          # UTF-8值范围外的额外字符，如逗号、句号、空格、生僻字等
regex = "[\u4e00-\u9fff]"                 # 正则表达式；若use_regex为false，则忽略此项
